TRUNCATE TABLE aers.demo ;

LOAD DATA INFILE '/tmp/DEMO10Q1.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;
 
LOAD DATA INFILE '/tmp/DEMO10Q2.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DEMO10Q3.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DEMO10Q4.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DEMO11Q1.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DEMO11Q2.TXT' REPLACE INTO TABLE aers.demo FIELDS TERMINATED BY '$' IGNORE 1 LINES;
