TRUNCATE TABLE aers.drug ;

LOAD DATA INFILE '/tmp/DRUG10Q1.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DRUG10Q2.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DRUG10Q3.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DRUG10Q4.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DRUG11Q1.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/DRUG11Q2.TXT' REPLACE INTO TABLE aers.drug FIELDS TERMINATED BY '$' IGNORE 1 LINES;
