TRUNCATE TABLE aers.indi;

LOAD DATA INFILE '/tmp/INDI10Q1.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/INDI10Q2.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/INDI10Q3.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/INDI10Q4.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/INDI11Q1.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/INDI11Q2.TXT' REPLACE INTO TABLE aers.indi FIELDS TERMINATED BY '$' IGNORE 1 LINES;