TRUNCATE TABLE aers.outc;

LOAD DATA INFILE '/tmp/OUTC10Q1.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/OUTC10Q2.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/OUTC10Q3.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/OUTC10Q4.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/OUTC11Q1.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/OUTC11Q2.TXT' REPLACE INTO TABLE aers.outc FIELDS TERMINATED BY '$' IGNORE 1 LINES;