TRUNCATE TABLE aers.reac;

LOAD DATA INFILE '/tmp/REAC10Q1.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/REAC10Q2.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/REAC10Q3.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/REAC10Q4.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/REAC11Q1.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/REAC11Q2.TXT' REPLACE INTO TABLE aers.reac FIELDS TERMINATED BY '$' IGNORE 1 LINES;