TRUNCATE TABLE aers.ther;

LOAD DATA INFILE '/tmp/THER10Q1.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/THER10Q2.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/THER10Q3.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/THER10Q4.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/THER11Q1.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;

LOAD DATA INFILE '/tmp/THER11Q2.TXT' REPLACE INTO TABLE aers.ther FIELDS TERMINATED BY '$' IGNORE 1 LINES;